export type ProductFormData = {
  // General
  name: string;
  category: number;
  description: string;
  // Image
  image: File[];
  // Properties
  isOrganic: boolean;
  isVegan: boolean;
  isGlutenFree: boolean;
  isGrazingAnimal: boolean;
  isGmoFree: boolean;
  // Pricing
  price: number;
  unit: string;
  vat: number;
  amount: number;
  // Delivery
  containerTypeId: number;
  deliveryCharge: number;
  deliveryOptionsIds: number[];
  // Availability
  regions: number[];
  // Internal
  sellersProductIdentifier: string;
  tags: string[];
  ean8: string;
  ean13: string;
};
