version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.1
    - 12.8.0
    - 12.8.3
    - 13.0.0
    - 13.0.13
    - 13.1.1
    - 13.1.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.34
    - 14.14.35
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: query-string
    versions:
    - 6.14.0
    - 6.14.1
  - dependency-name: "@hookform/resolvers"
    versions:
    - 1.3.4
    - 1.3.5
  - dependency-name: react-query
    versions:
    - 3.6.0
    - 3.8.2
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.0
  - dependency-name: "@sentry/react"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
  - dependency-name: "@sentry/tracing"
    versions:
    - 6.0.2
    - 6.0.4
  - dependency-name: "@date-io/date-fns"
    versions:
    - 2.10.6
    - 2.10.8
  - dependency-name: "@welldone-software/why-did-you-render"
    versions:
    - 6.0.5
