[build]
    base = "/"
    publish = "build/"
    command = 'sed -i -e "s/__PAGE_TITLE__/$CLIENT_NAME/g" public/index.html && sed -i -e "s/__PAGE_DESCRIPTION__/$CLIENT_NAME/g" public/index.html && npm run build'
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = false
