[build]
    base = "/"
    publish = "build/"
    command = 'sed -i -e "s/__PAGE_TITLE__/$REACT_APP_CLIENT_NAME/g" public/index.html && sed -i -e "s/__PAGE_DESCRIPTION__/$REACT_APP_CLIENT_NAME/g" public/index.html && wget https://storage.googleapis.com/mcsaxony-develop-static/favicon.png -O public/favicon.png && node src/scrtips/generate_favicons.js && sed -i -e "s|__FAVICONS__|$(tr -d '\n' < public/favicons.html)|g" public/index.html && npm run build'
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = false
